#!/usr/bin/env python3
"""Generate docs/STATS.md -- the single source of truth for project-total
figures. Every other doc/exhibit that cites a project-wide number (properties
on spine, court cases, legal-grade count, raw artifacts, etc.) should link
here instead of hardcoding its own copy -- hardcoded copies are exactly how
the project ended up with 5+ different "properties on spine" figures across
docs/CLAUDE.md before this script existed (2026-06-28 coherence review).

Pure local queries against Postgres + the raw store. No network. Safe to
re-run any time; re-running and re-committing this file IS how the project's
totals stay current -- there is no other update mechanism, so re-run after
any load script.

Run:
    .venv312/bin/python scripts/187_generate_stats.py
"""
from __future__ import annotations

import logging
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import psycopg2  # noqa: E402

from mariupol_seizures import config  # noqa: E402

log = logging.getLogger(__name__)
OUT = ROOT / "docs" / "STATS.md"
RAW = ROOT / "data" / "raw"


def q1(cur, sql: str, *args):
    cur.execute(sql, args)
    return cur.fetchone()[0]


def main() -> None:
    con = psycopg2.connect(config.DATABASE_URL)
    cur = con.cursor()

    properties = q1(cur, "SELECT count(*) FROM property")
    rd4u_null = q1(cur, "SELECT count(*) FROM property WHERE rd4u_category IS NULL")
    corroboration = q1(cur, "SELECT count(*) FROM corroboration")
    seizure_total = q1(cur, "SELECT count(*) FROM seizure_event")
    source_docs = q1(cur, "SELECT count(*) FROM source_document")
    cur.execute("SELECT stage, count(*) FROM seizure_event GROUP BY 1 ORDER BY 2 DESC")
    stages = cur.fetchall()
    distinct_courts = q1(
        cur, "SELECT count(DISTINCT court) FROM source_document WHERE court IS NOT NULL")

    # raw store: count files on disk, excluding .meta.json sidecars
    raw_files = sum(1 for p in RAW.glob("*") if not p.name.endswith(".meta.json"))
    raw_size = subprocess.run(["du", "-sh", str(RAW)], capture_output=True, text=True)
    raw_size_str = raw_size.stdout.split()[0] if raw_size.returncode == 0 else "?"

    # legal-grade: re-run the authoritative corroboration script and parse its summary
    # rather than re-deriving the family-grouping logic here (scripts/33 owns that
    # definition -- CLAUDE.md's "independent source family", not a generic source_doc
    # count, which earlier confused this exact number).
    corr = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "33_corroboration_report.py")],
        capture_output=True, text=True)
    # the script's own stdout format is "properties=N legal-grade(>=2 fam)=N
    # court-islands=N no-source=N"
    import re
    legal_grade = court_islands = no_source = None
    m = re.search(r"legal-grade\(>=2 fam\)=(\d+)\s+court-islands=(\d+)\s+no-source=(\d+)",
                  corr.stdout)
    if m:
        legal_grade, court_islands, no_source = (int(x) for x in m.groups())

    # district bezkhoz Mariupol grant rate (bezkhoz-filtered, the authoritative
    # rate -- NOT the legacy Case Study IV exhibit's 82.2%/2,666, which predates
    # the full-population crawl and isn't reproducible from any script in the repo)
    import json as J
    mariupol_rate = None
    dist_path = ROOT / "data" / "parsed" / "dnr_district_bezkhoz.json"
    if dist_path.exists():
        recs = J.loads(dist_path.read_text(encoding="utf-8"))
        mar = [r for r in recs if r["is_mariupol"]]
        decided = [r for r in mar if not r["rollup"].startswith("UNKNOWN")]
        granted = [r for r in decided if r["rollup"].startswith("LOSE")]
        rest = [r for r in recs if not r["is_mariupol"]]
        rest_dec = [r for r in rest if not r["rollup"].startswith("UNKNOWN")]
        rest_grant = [r for r in rest_dec if r["rollup"].startswith("LOSE")]
        mariupol_rate = {
            "total": len(mar), "decided": len(decided), "granted": len(granted),
            "pct": 100 * len(granted) / len(decided) if decided else 0,
            "rest_total": len(rest), "rest_decided": len(rest_dec),
            "rest_granted": len(rest_grant),
            "rest_pct": 100 * len(rest_grant) / len(rest_dec) if rest_dec else 0,
        }

    L = []
    A = L.append
    A("# Project statistics — single source of truth")
    A("")
    A("*Generated by `scripts/187_generate_stats.py` — do not hand-edit. "
      "Re-run after any load script and commit the diff. Other docs should "
      "link here (`docs/STATS.md`) rather than hardcode a copy of any figure "
      "below — hardcoded copies are exactly how the project accumulated 5+ "
      "conflicting \"properties on spine\" numbers before this file existed "
      "(coherence review, 2026-06-28).*")
    A("")
    A("## Evidence spine (PostgreSQL)")
    A("")
    A(f"| Metric | Value |")
    A(f"|---|---|")
    A(f"| Properties on spine | **{properties:,}** |")
    A(f"| — uncategorized (RD4U) | {rd4u_null:,} |")
    lg = f"{legal_grade:,}" if legal_grade is not None else "?"
    ci = f"{court_islands:,}" if court_islands is not None else "?"
    ns = f"{no_source:,}" if no_source is not None else "?"
    A(f"| Legal-grade (≥2 independent source families) | **{lg}** |")
    A(f"| Court-island properties (single-source, court only) | {ci} |")
    A(f"| No-source properties | {ns} |")
    A(f"| Corroboration rows | {corroboration:,} |")
    A(f"| Seizure-event rows (all stages) | {seizure_total:,} |")
    A(f"| Source-document rows (DB-registered, chain of custody) | {source_docs:,} |")
    A(f"| Distinct courts represented in source_document | {distinct_courts} |")
    A("")
    A("### Seizure events by stage")
    A("")
    A("| Stage | Count |")
    A("|---|---|")
    for stage, n in stages:
        A(f"| {stage} | {n:,} |")
    A("")
    A("## Raw evidence store (forensic, on disk — `data/raw/`)")
    A("")
    A(f"| Metric | Value |")
    A(f"|---|---|")
    A(f"| Raw artifact files (excl. `.meta.json` sidecars) | **{raw_files:,}** |")
    A(f"| Disk size | **{raw_size_str}** |")
    A("")
    A("Note the gap between this and `source_document` above: the raw store is "
      "append-only and holds *everything ever captured*; `source_document` is "
      "the subset formally loaded into Postgres with a chain-of-custody link. "
      "Historical figures like \"39,061 raw artifacts\" or \"211,900 registered "
      "artifacts\" in older docs were accurate at an earlier snapshot — they are "
      "not current and should be replaced with the figures above on next "
      "revision of those docs.")
    A("")
    A("## Occupation court layer (district + appellate + cassation)")
    A("")
    if mariupol_rate:
        A(f"**Mariupol, bezkhoz-confirmed cases only** (the authoritative rate — "
          f"supersedes the legacy Case Study IV exhibit figure of 82.2%/2,666, "
          f"which predates the full-population crawl and is not reproducible "
          f"from any script in this repo):")
        A("")
        A(f"- Total: {mariupol_rate['total']:,} · decided: "
          f"{mariupol_rate['decided']:,} · granted: {mariupol_rate['granted']:,} "
          f"· **grant rate: {mariupol_rate['pct']:.1f}%**")
        A(f"- Rest of DNR: total {mariupol_rate['rest_total']:,} · decided "
          f"{mariupol_rate['rest_decided']:,} · granted "
          f"{mariupol_rate['rest_granted']:,} · grant rate "
          f"**{mariupol_rate['rest_pct']:.1f}%**")
        A("")
    A("See `docs/dnr_district_first_instance_2026-06.md` (first instance, 26 "
      "courts) and `docs/dnr_bezkhoz_appellate_outcomes_2026-06.md` (ВС ДНР "
      "appeals) for full breakdowns and methodology.")
    A("")

    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"properties={properties} legal_grade={legal_grade} "
          f"raw_files={raw_files} mariupol_rate={mariupol_rate}")
    print(f"-> {OUT}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    main()
